os: 
- windows
#- osx
language: go

git:
  depth: 3
  quiet: true
go:
  # - 1.10.x
- "1.11.5"
#  - "1.11.6"
  # - 1.12.x

# services:
#   - rabbitmq

# env:
#   - GO111MODULE=on AMQP_URL=amqp://guest:guest@127.0.0.1:5672/

# before_install:
#   - go get -v golang.org/x/lint/golint
before_script:
- if [[ $TRAVIS_OS_NAME == windows ]]; then
  mkdir -p ${TRAVIS_HOME}/gopath/src/github.com/iotexproject/iotex-core
  tar -Pczf ${TRAVIS_TMPDIR}/src_archive.tar.gz -C ${TRAVIS_BUILD_DIR} . && tar -Pxzf ${TRAVIS_TMPDIR}/src_archive.tar.gz -C ${TRAVIS_HOME}/gopath/src/github.com/iotexproject/iotex-core
  fi
script:
- ./go.test.sh
after_success:
- bash <(curl -s https://codecov.io/bash)
  # - go test -cpu=1,2 -v -tags integration ./...

