[[constraint]]
  name = "github.com/mattn/go-sqlite3"
  version = "~1.10.0"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "~1.4.0"
[[constraint]]
  name = "go.etcd.io/bbolt"
  version = "^v1.3.1-etcd.8"

[[constraint]]
  branch = "master"
  name = "github.com/coopernurse/barrister-go"

[[constraint]]
  name = "github.com/golang/mock"
  version = "~1.2.0"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.3.0"

[[constraint]]
  name = "github.com/golang/groupcache"
  revision = "5b532d6fd5efaf7fa130d4e859a2fde0fc3a9e1b"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "~0.8.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "~1.3.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "~2.2.0"

[[constraint]]
  name = "go.uber.org/config"
  version = "~1.3.0"

[[constraint]]
  name = "go.uber.org/zap"
  version = "~1.9.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "~0.9.0"

[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  revision = "2bbee71fbe61def241832e800b4f0bd24d4beb89"
  source = "github.com/iotexproject/go-ethereum"

[[constraint]]
  name = "github.com/iotexproject/go-fsm"
  version = "v1.0.0"

[[constraint]]
  name = "github.com/iotexproject/go-p2p"
  version = "v0.2.1"

[[constraint]]
  name = "github.com/iotexproject/iotex-election"
  version = "v0.1.3"

[prune]
  go-tests = true
  unused-packages = true

  [[prune.project]]
      name = "github.com/ethereum/go-ethereum"
      unused-packages = false

[[constraint]]
  name = "github.com/cenkalti/backoff"
  version = "2.1.1"
