chain:
  chainDBPath: /var/data/chain.db
  trieDBPath: /var/data/trie.db
  indexDBPath: /var/data/index.db
  candidateIndexDBPath: /var/data/candidate.index.db
  gravityChainDB:
    dbPath: /var/data/poll.db
system:
  systemLogDBPath: /var/log/systemlog.db
log:
  zap:
    level: info
    encoding: json
    disableStacktrace: true
    outputPaths: ["stderr", "stdout"]
    errorOutputPaths: ["stderr"]
  stderrRedirectFile: /var/log/s.log
  stdLogRedirect: true
  lumberjack:
    maxsize: 10
    maxage: 30
    maxbackups: 100
    localtime: true