name: ci

on:

  pull_request:
    branches: [ master ]

permissions:
  contents: read
  pull-requests: read
  packages: write

env:
  GO111MODULE: on

jobs:
  ci:
    name: ci flow
    runs-on: self-hosted
    steps:

    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: errcheck
      uses: reviewdog/action-golangci-lint@v2
      with:
        golangci_lint_flags: "--disable-all -E errcheck"
        tool_name: errcheck
        level: info
        
    - name: run-test
      id: unittest
      if: github.event_name == 'push'
      run: |
        go get -u github.com/dave/courtney@038390a12707e2d91979d2ca77a71597f4afe400
        ./go.test.sh
        bash <(curl -s https://codecov.io/bash)
        go test -run=XXX -bench=. $(go list ./crypto)
        
    - name: make-minicluster
      id: minicluster
      if: github.event_name == 'push'
      run: |
        make minicluster
