name: ci

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read
  packages: write

env:
  GO111MODULE: on

jobs:
  ci:
    name: ci flow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # with:
        #   submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.13
          cache: false
      
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          only-new-issues: true
          
      - name: Build Go
        run: go build ./...

      - name: Run Test
        id: unittest
        shell: bash
        run: |
          go install github.com/dave/courtney@latest
          go clean -cache -modcache -r
          go mod tidy
          ./go.test.sh
          #make test
          go test -run=XXX -bench=. $(go list ./crypto)
          bash <(curl -s https://codecov.io/bash)

      - name: Make Minicluster
        if: github.event.pull_request.merged == true
        id: minicluster
        shell: bash
        run: |
          make minicluster
