name: ci

on:

  pull_request:
    branches: [ master ]
    #types: [opened]

permissions:
  contents: read
  pull-requests: read
  packages: write

env:
  GO111MODULE: on

jobs:
  ci:
    name: ci flow
    runs-on: self-hosted
    steps:

    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: errcheck
      uses: reviewdog/action-golangci-lint@v2
      with:
        golangci_lint_flags: "--disable-all -E errcheck"
        tool_name: errcheck
        level: info

