name: Release

on:
  push:
    branches: [test]
    tags:
      - "v*"

jobs:
  build:
    name: Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: ioctl-linux-amd64
            asset_name: ioctl-linux-amd64
          - os: windows-latest
            artifact_name: ioctl-windows-amd64.exe
            asset_name: ioctl-windows-amd64.exe
          - os: macos-latest
            artifact_name: ioctl-darwin-amd64
            asset_name: ioctl-darwin-amd64
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.5

      - name: make ioctl
        run: |
          set CGO_ENABLED=1 
          set GOARCH=amd64
          go build -tags netgo -o ./${{ matrix.artifact_name }} -v ./tools/ioctl

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}

      - name: Configure GPG and create artifacts
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          export GPG_TTY=$(tty)
          echo "$GPG_SIGNING_KEY" | gpg --batch --import
          echo "$GPG_PASSPHRASE" | gpg --passphrase-fd 0 --pinentry-mode loopback --batch -ab ./${{ matrix.artifact_name }}
          mv *tar.gz* ..

      - name: Upload signature
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.artifact_name }}.asc
          path: ./${{ matrix.artifact_name }}.asc
