name: Release 

on:
  push:
    tags:
    - 'v*' 

jobs:
  build:
    name: Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: ioctl-linux-amd64
            asset_name: ioctl-linux-amd64
          # - os: windows-latest
          #   artifact_name: ioctl-windows-amd64.exe
          #   asset_name: ioctl-windows-amd64.exe
          # - os: macos-latest
          #   artifact_name: ioctl-darwin-amd64
          #   asset_name: ioctl-darwin-amd64
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: make ioctl
        run: |

          make ioctl-cross
          
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./bin/ioctl/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}